[pytest]
markers = 
  smoke: marks tests as smoke (deselect with -m "not smoke")
  slow

# stops truncating of test results output
truncation_limit_lines = 0
truncation_limit_chars = 0

# creates a JUnit style report
junit_suite_name = my_juint_suite
junit_duration_report = call # this reports time of test only, does not include set up and teardown
